# =============================================================================
#
# @package    RPi5 netmonitor containers
# @container  netmonitor (complete installation)
# @name       Dockerfile
# @purpose    Container definition
# @version    v0.0.1  2026-01-15
# @author     pierre@amultis.dev
# @copyright  (C) Pierre Veelen
#
# =============================================================================
FROM ubuntu:24.04

# Update, upgrade and install required packages
RUN apt-get update && apt-get upgrade -y && apt-get install nano net-tools traceroute iputils-ping -y

WORKDIR /opt/netmonitor

COPY ./netmonitor/ /opt/netmonitor

RUN /opt/netmonitor/install_complete.sh 


#EXPOSE 8080/udp

# for debug and test mode
# =======================
CMD ["tail", "-f", "/dev/null"]

# for production mode
# =======================
#CMD ["python", "/app/py_app/netmonitor.py"]
