# =============================================================================
#
# @package    RPi5 netmonitor containers
# @container  netmonitor (complete installation)
# @name       Dockerfile
# @purpose    Container definition
# @version    v0.0.5  2026-02-20
# @author     pierre@amultis.dev
# @copyright  (C) Pierre Veelen
#
# =============================================================================
FROM ubuntu:24.04

# Let install script know it is not running on bare server but in docker
ENV IS_DOCKER=true

# prevent prompts from apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update, upgrade and install required baseline packages for network testing and editing
RUN apt-get update && apt-get upgrade -y && apt-get install nano net-tools traceroute iproute2 iputils-ping -y

# install required packages for netmonitor install_complete.sh script
RUN apt-get install iproute2 lsb-release -y

# explicitly set timezone data in this container
# use TZ variable from docker-compose
RUN apt-get install tzdata -y

WORKDIR /opt/netmonitor

COPY ./netmonitor/ /opt/netmonitor

#RUN /opt/netmonitor/install_complete.sh 

#EXPOSE 8080/udp

# for debug and test mode
# =======================
CMD ["sleep", "infinity"]

# for production mode
# =======================
#CMD ["python", "/app/py_app/netmonitor.py"]
